package com.jea.cards.inputs;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.jea.cards.dto.CardsDetailDto;
import com.jea.cards.service.CardsService;

import jakarta.annotation.PostConstruct;


@Component
public class CardsRecords {
	
	@Autowired
	private CardsService cardsService;
	
	@PostConstruct
	public void createListOfRecords() {
		List<String> listOfMobileNumber = Stream.of("9999999999","9999988888","8888899999","8888888888").collect(Collectors.toList());
		List<CardsDetailDto> autoGeneratedCardsList = listOfMobileNumber.stream()
				.map(mobileNumber -> cardsService.saveNewCard(mobileNumber)).collect(Collectors.toList());
		System.out.println("Auto Generated Cards ::: ");
		autoGeneratedCardsList.forEach(System.out::println);
	}
	
}