spring:
  application:
    name: loans
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:loans
    username: loans
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9005

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    version: 0.0.1
    description: loans microservice project
  contact: '+1234567890'

#Configure eureka client properties
eureka:
  client:
    service-url:
#'/' is very importamt at last, otherwise defaultZone url won't pick-up
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true