package com.jea.accounts.inputs;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.jea.accounts.dto.CustomerDetailsDto;
import com.jea.accounts.service.AccountsService;

import jakarta.annotation.PostConstruct;

@Component
public class AccountsRecords {

	@Autowired
	private AccountsService accountsService;

	@PostConstruct
	public void createListOfAccounts() {

		List<CustomerDetailsDto> listOfAutoGeneratedCustomerAccountDetails = new ArrayList<>();

		String[] nameList = { "Thor", "Iron Man", "Captain America", "Hulk" };
		String[] emailList = { "thor@email.com", "ironman@email.com", "captainamerica@email.com", "hulk@email.com" };
		String[] moblieNumberList = { "9999999999", "9999988888", "8888899999", "8888888888" };

		for (int index = 0; index < nameList.length; index++) {
			CustomerDetailsDto customerDetailsDto = new CustomerDetailsDto();
			customerDetailsDto.setName(nameList[index]);
			customerDetailsDto.setEmail(emailList[index]);
			customerDetailsDto.setMobileNumber(moblieNumberList[index]);

			listOfAutoGeneratedCustomerAccountDetails.add(accountsService.createAccount(customerDetailsDto));
		}
		System.out.println("List Of AutoGenerated Customer-Account Details ::: ");
		listOfAutoGeneratedCustomerAccountDetails.forEach(System.out::println);
	}
}