spring:
  application:
    name: cards
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cards
    username: cards
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9004

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    version: 0.0.1
    description: cards microservice project
  contact: '+1234567890'
